# Generated by Django 2.1.7 on 2019-09-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convergence_Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Board_Title', models.CharField(max_length=150, null=True)),
                ('Board_Content', models.TextField()),
                ('Board_CreateDate', models.DateTimeField(null=True)),
                ('Board_ClassCode', models.CharField(blank=True, choices=[('1', '지식재산 디자인기반 소프트웨어'), ('2', '정보처리와 소프트웨어 지식재산'), ('3', '글로벌 엔터테인먼트'), ('4', '개인 비행체 프로토타입 설계')], default='기타', max_length=10, null=True)),
                ('Board_Files', models.FileField(blank=True, null=True, upload_to='')),
                ('Board_hits', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Convergence_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
                ('recommend', models.IntegerField(default=0)),
                ('comment_Board', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='convergence.Convergence_Board')),
            ],
        ),
        migrations.CreateModel(
            name='Convergence_Comment_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_reply', models.CharField(blank=True, max_length=150, null=True, verbose_name='대댓글')),
                ('reply_recommend', models.IntegerField(default=0)),
                ('reply_createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('convergence_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='convergence.Convergence_Comment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Convergence_ID', models.CharField(max_length=20, null=True)),
                ('Convergence_PW', models.CharField(max_length=20, null=True)),
                ('Convergence_Name', models.CharField(max_length=20, null=True)),
                ('Convergence_Dept', models.CharField(max_length=20, null=True)),
                ('Convergence_grade', models.CharField(max_length=2, null=True)),
                ('Convergence_PhoneNumber', models.CharField(max_length=20, null=True)),
                ('rank', models.CharField(choices=[('1', '시스템관리자'), ('2', '사용자')], default='2', max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='convergence_comment_reply',
            name='reply_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='convergence.User'),
        ),
        migrations.AddField(
            model_name='convergence_comment',
            name='comment_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='convergence.User'),
        ),
        migrations.AddField(
            model_name='convergence_board',
            name='Board_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='convergence.User'),
        ),
    ]
