# Generated by Django 2.1.7 on 2019-10-09 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0003_auto_20190908_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convergence_Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Convergence_File', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='convergence_board',
            name='Board_Files',
        ),
        migrations.AddField(
            model_name='convergence_files',
            name='Board_File',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='convergence.Convergence_Board'),
        ),
    ]
