# Generated by Django 2.1.7 on 2019-10-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0004_auto_20191009_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convergence_files',
            name='Convergence_File',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
